# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 02:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='course',
            name='credithours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='fall',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prereq',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='spring',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
